language: ruby

rvm:
  - 2.7

jobs:
  include:
    - stage: ruby gems release
      rvm: "2.7"
      script: echo "Deploying to ruby gems ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_TOKEN
        gem: appwrite
        on:
          tags: true