package io.appwrite.models;

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types ./types`.
 */

import java.util.Objects;
import io.appwrite.models.Authors;

public class BooksZines {

    public enum BooksZinesKind {
        HARDCOVER,
        SOFTCOVER,
        ;
    }

    private String title;
    private List<Authors> author;
    private String rdflag;
    private BooksZinesKind kind;

    public BooksZines() {
    }

    public BooksZines(
        String title,
        List<Authors> author,
        String rdflag,
        BooksZinesKind kind
    ) {
        this.title = title;
        this.author = author;
        this.rdflag = rdflag;
        this.kind = kind;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<Authors> getAuthor() {
        return author;
    }

    public void setAuthor(List<Authors> author) {
        this.author = author;
    }

    public String getRdflag() {
        return rdflag;
    }

    public void setRdflag(String rdflag) {
        this.rdflag = rdflag;
    }

    public BooksZinesKind getKind() {
        return kind;
    }

    public void setKind(BooksZinesKind kind) {
        this.kind = kind;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        BooksZines that = (BooksZines) obj;
        return Objects.equals(title, that.title) &&
          Objects.equals(author, that.author) &&
          Objects.equals(rdflag, that.rdflag) &&
          Objects.equals(kind, that.kind);
    }

    @Override
    public int hashCode() {
        return Objects.hash(title, author, rdflag, kind);
    }

    @Override
    public String toString() {
        return "BooksZines{" +
                "title=" + title + ", " +
                "author=" + author + ", " +
                "rdflag=" + rdflag + ", " +
                "kind=" + kind +
                '}';
    }
}
