package io.appwrite.models

import BooksZines

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types ./types`.
 */

enum class AuthorsStatus {
    ACTIVE,
    IN_ACTIVE,
    IN_ACTIVE,
    9LIVES,
    IN_ACTIVE
}

data class Authors(
    val id: String,
    val fullName: String,
    val bio: String?,
    val age: Long?,
    val rating: Float,
    val verified: Boolean?,
    val joinedAt: String,
    val tags: List<String>?,
    val status: AuthorsStatus,
    val books: List<BooksZines>?,
    val home: List<Double>?,
    val route: List<List<Double>>,
    val region: List<List<List<Double>>>,
    val weirdKey: String
)
