<?php
namespace Appwrite\Models;

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types ./types`.

enum AuthorsStatus: string {
    case ACTIVE = 'active';
    case IN_ACTIVE = 'in-active';
    case IN_ACTIVE = 'in active';
    case 9LIVES = '9lives';
    case IN_ACTIVE = 'in_active';
}

class Authors {
    private string $$id;
    private string $full name;
    private string|null $bio;
    private int|null $age;
    private float $rating;
    private bool|null $verified;
    private string $joined-at;
    private array $tags;
    private AuthorsStatus $status;
    private array|null $books;
    private array|null $home;
    private array $route;
    private array $region;
    private string $weird key!;

    public function __construct(
        string $$id,
        string $full name,
        ?string $bio = null,
        ?int $age = null,
        float $rating,
        ?bool $verified = null,
        string $joined-at,
        ?array $tags = null,
        AuthorsStatus $status,
        ?array $books = null,
        ?array $home = null,
        array $route,
        array $region,
        string $weird key!
    ) {
        $this->$id = $$id;
        $this->full name = $full name;
        $this->bio = $bio;
        $this->age = $age;
        $this->rating = $rating;
        $this->verified = $verified;
        $this->joined-at = $joined-at;
        $this->tags = $tags;
        $this->status = $status;
        $this->books = $books;
        $this->home = $home;
        $this->route = $route;
        $this->region = $region;
        $this->weird key! = $weird key!;
    }

    public function getId(): string {
        return $this->$id;
    }

    public function setId(string $$id): void {
        $this->$id = $$id;
    }

    public function getFullName(): string {
        return $this->full name;
    }

    public function setFullName(string $full name): void {
        $this->full name = $full name;
    }

    public function getBio(): string|null {
        return $this->bio;
    }

    public function setBio(string|null $bio): void {
        $this->bio = $bio;
    }

    public function getAge(): int|null {
        return $this->age;
    }

    public function setAge(int|null $age): void {
        $this->age = $age;
    }

    public function getRating(): float {
        return $this->rating;
    }

    public function setRating(float $rating): void {
        $this->rating = $rating;
    }

    public function getVerified(): bool|null {
        return $this->verified;
    }

    public function setVerified(bool|null $verified): void {
        $this->verified = $verified;
    }

    public function getJoinedAt(): string {
        return $this->joined-at;
    }

    public function setJoinedAt(string $joined-at): void {
        $this->joined-at = $joined-at;
    }

    public function getTags(): array {
        return $this->tags;
    }

    public function setTags(array $tags): void {
        $this->tags = $tags;
    }

    public function getStatus(): AuthorsStatus {
        return $this->status;
    }

    public function setStatus(AuthorsStatus $status): void {
        $this->status = $status;
    }

    public function getBooks(): array|null {
        return $this->books;
    }

    public function setBooks(array|null $books): void {
        $this->books = $books;
    }

    public function getHome(): array|null {
        return $this->home;
    }

    public function setHome(array|null $home): void {
        $this->home = $home;
    }

    public function getRoute(): array {
        return $this->route;
    }

    public function setRoute(array $route): void {
        $this->route = $route;
    }

    public function getRegion(): array {
        return $this->region;
    }

    public function setRegion(array $region): void {
        $this->region = $region;
    }

    public function getWeirdKey(): string {
        return $this->weird key!;
    }

    public function setWeirdKey(string $weird key!): void {
        $this->weird key! = $weird key!;
    }
}
