package typegen

import (
	"fmt"
	"slices"
	"strings"
)

// Two things set this emitter apart from the rest:
//
//   - it ignores --strict completely. Property names are always PascalCase and
//     constructor parameters always camelCase, so `cs.loose` and `cs.strict`
//     are byte-identical files.
//   - optionality keys off `required` alone, not the required-and-null-default
//     pair every other emitter uses, so an optional attribute is `T?` even
//     without an explicit null default.
//
// Geometry attributes have no branch in From(), so point, linestring and
// polygon are all constructed as `default` -- a null the property type does not
// admit. Reproduced, like the rest of this package's inherited defects.
type CSharp struct{}

// csharpStringTypes are the types From() reads with ToString().
var csharpStringTypes = []string{
	"string", "text", "varchar", "mediumtext", "longtext", "datetime", "email",
}

// Type implements Language.
func (c CSharp) Type(attribute Attribute, collections []Collection, collectionName string) (string, error) {
	var literal string

	switch attribute.Type {
	case AttributeTypeString, AttributeTypeText, AttributeTypeVarchar,
		AttributeTypeMediumText, AttributeTypeLongText, AttributeTypeDateTime:
		literal = "string"
		if attribute.Format == AttributeTypeEnum {
			literal = ToPascalCase(collectionName) + ToPascalCase(attribute.Key)
		}
	case AttributeTypeInteger:
		literal = "long"
	case AttributeTypeFloat:
		literal = "double"
	case AttributeTypeBoolean:
		literal = "bool"
	case AttributeTypeRelationship:
		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		literal = ToPascalCase(related.Name)
		if IsRelationshipList(attribute) {
			literal = "List<" + literal + ">"
		}
	case AttributeTypePoint:
		literal = "List<double>"
	case AttributeTypeLineString:
		literal = "List<List<double>>"
	case AttributeTypePolygon:
		literal = "List<List<List<double>>>"
	default:
		return "", &UnknownAttributeTypeError{Type: attribute.Type}
	}

	if attribute.Array {
		literal = "List<" + literal + ">"
	}
	// `required` alone, unlike the nullable pair used elsewhere.
	if !attribute.Required {
		literal += "?"
	}

	return literal, nil
}

// SingleFile implements Language.
func (c CSharp) SingleFile() bool { return false }

// FileName implements Language.
func (c CSharp) FileName(collection *Collection) string {
	return ToPascalCase(collection.Name) + ".cs"
}

// Render implements Language.
//
// strict is accepted to satisfy Language and deliberately unused: the C#
// template never reads it.
func (c CSharp) Render(collections []Collection, current *Collection, _ bool, invocation string) (string, error) {
	var out strings.Builder

	// The trailing space after "CLI." is in the template.
	out.WriteString("/// This file is auto-generated by the Appwrite CLI. \n")
	fmt.Fprintf(&out, "/// You can regenerate it by running `appwrite %s`.\n\n", invocation)
	out.WriteString("#nullable enable\nusing System;\nusing System.Collections.Generic;\n")
	out.WriteString("using System.Linq;\nusing System.Text.Json.Serialization;\n\n")
	out.WriteString("namespace Appwrite.Models\n{\n")

	className := ToPascalCase(current.Name)

	for _, attribute := range current.Attributes {
		if attribute.Format != AttributeTypeEnum {
			continue
		}

		fmt.Fprintf(&out, "\npublic enum %s%s {\n", className, ToPascalCase(attribute.Key))
		for index, element := range attribute.Elements {
			separator := ""
			if index < len(attribute.Elements)-1 {
				separator = ","
			}
			fmt.Fprintf(&out, "    [JsonPropertyName(\"%s\")]\n    %s%s\n",
				element, ToPascalCase(element), separator)
		}
		out.WriteString("}\n")
	}

	// One unconditional blank line closes the enum section, whether or not any
	// enum was emitted.
	fmt.Fprintf(&out, "\npublic class %s\n{\n", className)

	types := make([]string, len(current.Attributes))
	properties := make([]string, len(current.Attributes))
	parameters := make([]string, len(current.Attributes))
	for index, attribute := range current.Attributes {
		literal, err := c.Type(attribute, collections, current.Name)
		if err != nil {
			return "", err
		}
		types[index] = literal
		properties[index] = ToPascalCase(attribute.Key)
		parameters[index] = ToCamelCase(attribute.Key)

		fmt.Fprintf(&out, "    [JsonPropertyName(\"%s\")]\n    public %s %s { get; private set; }\n\n",
			attribute.Key, literal, properties[index])
	}

	comma := func(index int) string {
		if index < len(current.Attributes)-1 {
			return ","
		}

		return ""
	}

	fmt.Fprintf(&out, "\n    public %s(\n", className)
	for index := range current.Attributes {
		fmt.Fprintf(&out, "        %s %s%s\n", types[index], parameters[index], comma(index))
	}
	out.WriteString("    )\n    {\n")
	for index := range current.Attributes {
		fmt.Fprintf(&out, "        %s = %s;\n", properties[index], parameters[index])
	}
	out.WriteString("    }\n\n")

	fmt.Fprintf(&out,
		"    public static %s From(Dictionary<string, object> map) => new %s(\n", className, className)
	for index, attribute := range current.Attributes {
		expression, err := c.fromExpression(attribute, collections, className, types[index])
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&out, "        %s: %s%s\n", parameters[index], expression, comma(index))
	}
	out.WriteString("    );\n\n")

	out.WriteString("    public Dictionary<string, object?> ToMap() => new Dictionary<string, object?>()\n    {\n")
	for index, attribute := range current.Attributes {
		fmt.Fprintf(&out, "        { \"%s\", %s }%s\n",
			attribute.Key, c.toMapExpression(attribute, properties[index]), comma(index))
	}
	out.WriteString("    };\n}\n}\n")

	return out.String(), nil
}

// fromExpression builds one argument of the From() call.
func (c CSharp) fromExpression(attribute Attribute, collections []Collection, className, literal string) (string, error) {
	key := attribute.Key

	switch {
	case attribute.Format == AttributeTypeEnum:
		enumName := "Models." + className + ToPascalCase(key)
		if attribute.Array {
			return fmt.Sprintf(
				"((IEnumerable<object>)map[\"%s\"]).Select(e => Enum.Parse<%s>(e.ToString()!, true)).ToList()",
				key, enumName), nil
		}

		return fmt.Sprintf("Enum.Parse<%s>(map[\"%s\"].ToString()!, true)", enumName, key), nil

	case attribute.Type == AttributeTypeRelationship:
		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}
		relatedClass := ToPascalCase(related.Name)

		if IsRelationshipList(attribute) || attribute.Array {
			return fmt.Sprintf(
				"((IEnumerable<object>)map[\"%s\"]).Select(it => Models.%s.From((Dictionary<string, object>)it)).ToList()",
				key, relatedClass), nil
		}

		return fmt.Sprintf("Models.%s.From((Dictionary<string, object>)map[\"%s\"])", relatedClass, key), nil

	case attribute.Array:
		switch {
		case slices.Contains(csharpStringTypes, attribute.Type):
			// The .Where filter is applied when the attribute IS required,
			// which is the opposite of what filtering nulls would be for.
			filter := ""
			if attribute.Required {
				filter = ".Where(x => x != null)"
			}

			return fmt.Sprintf(
				"((IEnumerable<object>)map[\"%s\"]).Select(x => x?.ToString())%s.ToList()!", key, filter), nil
		case attribute.Type == AttributeTypeInteger:
			return fmt.Sprintf("((IEnumerable<object>)map[\"%s\"]).Select(x => %sConvert.ToInt64(x)).ToList()",
				key, nullGuard(attribute, "long")), nil
		case attribute.Type == AttributeTypeFloat:
			return fmt.Sprintf("((IEnumerable<object>)map[\"%s\"]).Select(x => %sConvert.ToDouble(x)).ToList()",
				key, nullGuard(attribute, "double")), nil
		case attribute.Type == AttributeTypeBoolean:
			return fmt.Sprintf("((IEnumerable<object>)map[\"%s\"]).Select(x => %s(bool)x).ToList()",
				key, nullGuard(attribute, "bool")), nil
		}

		// An array of a geometry type matches no branch and produces nothing
		// at all -- not even `default`.
		return "", nil

	case attribute.Type == AttributeTypeInteger:
		return mapGuard(attribute, key) + fmt.Sprintf("Convert.ToInt64(map[\"%s\"])", key), nil

	case attribute.Type == AttributeTypeFloat:
		return mapGuard(attribute, key) + fmt.Sprintf("Convert.ToDouble(map[\"%s\"])", key), nil

	case attribute.Type == AttributeTypeBoolean:
		return fmt.Sprintf("(%s)map[\"%s\"]", literal, key), nil

	case slices.Contains(csharpStringTypes, attribute.Type):
		optional, force := "", "!"
		if !attribute.Required {
			optional, force = "?", ""
		}

		return fmt.Sprintf("map[\"%s\"]%s.ToString()%s", key, optional, force), nil
	}

	// Geometry types land here.
	return "default", nil
}

// nullGuard is the inline null check the array branches prepend for an optional
// attribute.
func nullGuard(attribute Attribute, cast string) string {
	if attribute.Required {
		return ""
	}

	return fmt.Sprintf("x == null ? (%s?)null : ", cast)
}

// mapGuard is the equivalent for a single value, which tests the map entry
// rather than the element.
func mapGuard(attribute Attribute, key string) string {
	if attribute.Required {
		return ""
	}

	return fmt.Sprintf("map[\"%s\"] == null ? null : ", key)
}

// toMapExpression builds one value of the ToMap() dictionary.
func (c CSharp) toMapExpression(attribute Attribute, property string) string {
	switch {
	case attribute.Format == AttributeTypeEnum:
		if attribute.Array {
			return property + "?.Select(e => e.ToString()).ToList()"
		}

		return property + "?.ToString()"

	case attribute.Type == AttributeTypeRelationship:
		if IsRelationshipList(attribute) || attribute.Array {
			return property + "?.Select(e => e.ToMap()).ToList()"
		}

		return property + "?.ToMap()"
	}

	return property
}
