package typegen

import (
	"fmt"
	"slices"
	"sort"
	"strings"
)

// Dart is the only emitter that reorders attributes: required ones come first,
// because a Dart named-parameter constructor puts `required this.x` before the
// optional ones. The sort is stable, so attributes keep their relative order
// within each group -- Array#sort has been stable since ES2019, and matching
// that is what makes the generated field order reproducible.
//
// Like C#, optionality keys off `required` alone rather than the
// required-and-null-default pair. Geometry attributes have no branch in
// fromMap(), so a point or polygon is constructed from an empty expression --
// `route: ,` -- which does not parse. Reproduced, as elsewhere in this package.
type Dart struct{}

// dartStringTypes are the types fromMap() reads with toString().
var dartStringTypes = []string{
	"string", "text", "varchar", "mediumtext", "longtext", "email", "datetime",
}

// Type implements Language.
func (d Dart) Type(attribute Attribute, collections []Collection, collectionName string) (string, error) {
	var literal string

	switch attribute.Type {
	case AttributeTypeString, AttributeTypeText, AttributeTypeVarchar,
		AttributeTypeMediumText, AttributeTypeLongText, AttributeTypeDateTime:
		literal = "String"
		if attribute.Format == AttributeTypeEnum {
			literal = ToPascalCase(collectionName) + ToPascalCase(attribute.Key)
		}
	case AttributeTypeInteger:
		literal = "int"
	case AttributeTypeFloat:
		literal = "double"
	case AttributeTypeBoolean:
		literal = "bool"
	case AttributeTypeRelationship:
		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		literal = ToPascalCase(related.Name)
		if IsRelationshipList(attribute) {
			literal = "List<" + literal + ">"
		}
	case AttributeTypePoint:
		literal = "List<double>"
	case AttributeTypeLineString:
		literal = "List<List<double>>"
	case AttributeTypePolygon:
		literal = "List<List<List<double>>>"
	default:
		return "", &UnknownAttributeTypeError{Type: attribute.Type}
	}

	if attribute.Array {
		literal = "List<" + literal + ">"
	}
	if !attribute.Required {
		literal += "?"
	}

	return literal, nil
}

// SingleFile implements Language.
func (d Dart) SingleFile() bool { return false }

// FileName implements Language.
func (d Dart) FileName(collection *Collection) string {
	return ToSnakeCase(collection.Name) + ".dart"
}

// requiredFirst returns the attributes with required ones ahead of optional
// ones, preserving relative order within each group.
func requiredFirst(attributes []Attribute) []Attribute {
	ordered := slices.Clone(attributes)
	sort.SliceStable(ordered, func(i, j int) bool {
		return ordered[i].Required && !ordered[j].Required
	})

	return ordered
}

// Render implements Language.
func (d Dart) Render(collections []Collection, current *Collection, strict bool, invocation string) (string, error) {
	var out strings.Builder

	// The trailing space after "CLI." is in the template.
	out.WriteString("// This file is auto-generated by the Appwrite CLI. \n")
	fmt.Fprintf(&out, "// You can regenerate it by running `appwrite %s`.\n", invocation)

	attributes := requiredFirst(current.Attributes)

	imported := map[string]bool{}
	for _, attribute := range attributes {
		if attribute.Type != AttributeTypeRelationship {
			continue
		}

		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		module := ToSnakeCase(related.Name)
		if imported[module] {
			continue
		}
		imported[module] = true

		fmt.Fprintf(&out, "import '%s.dart';\n", module)
	}

	// Emitted whether or not anything was imported.
	out.WriteString("\n")

	className := ToPascalCase(current.Name)

	for _, attribute := range attributes {
		if attribute.Format != AttributeTypeEnum {
			continue
		}

		enumName := className + ToPascalCase(attribute.Key)
		members := generateEnumMembers(attribute.Elements)

		fmt.Fprintf(&out, "enum %s {\n", enumName)
		for index, member := range members {
			terminator := ";"
			if index < len(members)-1 {
				terminator = ","
			}
			fmt.Fprintf(&out, "  %s(\"%s\")%s\n", member.Key, member.Value, terminator)
		}
		fmt.Fprintf(&out, "\n  const %s(this.value);\n  final String value;\n\n", enumName)
		fmt.Fprintf(&out, "  static %s? fromValue(String? value) {\n", enumName)
		out.WriteString("    if (value == null) return null;\n")
		fmt.Fprintf(&out,
			"    return %s.values.firstWhere((element) => element.value == value);\n  }\n}\n\n", enumName)
	}

	names := make([]string, len(attributes))
	for index, attribute := range attributes {
		names[index] = EscapeXML(PropertyName(attribute, strict))
	}

	comma := func(index int) string {
		if index < len(attributes)-1 {
			return ","
		}

		return ""
	}

	fmt.Fprintf(&out, "class %s {\n", className)
	for index, attribute := range attributes {
		literal, err := d.Type(attribute, collections, current.Name)
		if err != nil {
			return "", err
		}

		fmt.Fprintf(&out, "  %s %s;\n", literal, names[index])
	}

	fmt.Fprintf(&out, "\n  %s(", className)
	if len(attributes) > 0 {
		out.WriteString("{\n")
		for index, attribute := range attributes {
			required := ""
			if attribute.Required {
				required = "required "
			}
			fmt.Fprintf(&out, "    %sthis.%s%s\n", required, names[index], comma(index))
		}
		out.WriteString("  }")
	}
	out.WriteString(");\n\n")

	fmt.Fprintf(&out, "  factory %s.fromMap(Map<String, dynamic> map) {\n", className)
	fmt.Fprintf(&out, "    return %s(", className)
	if len(attributes) > 0 {
		out.WriteString("\n")
		for index, attribute := range attributes {
			expression, err := d.fromMapExpression(attribute, collections, className)
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&out, "      %s: %s%s\n", names[index], expression, comma(index))
		}
		out.WriteString("    ")
	}
	out.WriteString(");\n  }\n\n")

	out.WriteString("  Map<String, dynamic> toMap() {\n    return {\n")
	for index, attribute := range attributes {
		fmt.Fprintf(&out, "      '%s': %s%s\n",
			EscapeXML(attribute.Key), d.toMapExpression(attribute, names[index]), comma(index))
	}
	out.WriteString("    };\n  }\n}\n")

	return out.String(), nil
}

// fromMapExpression builds one argument of the fromMap() constructor call.
func (d Dart) fromMapExpression(attribute Attribute, collections []Collection, className string) (string, error) {
	key := EscapeXML(attribute.Key)

	switch {
	case slices.Contains(dartStringTypes, attribute.Type):
		if attribute.Format == AttributeTypeEnum {
			enumName := className + ToPascalCase(attribute.Key)
			switch {
			case attribute.Array:
				return fmt.Sprintf(
					"(map['%s'] as List<dynamic>?)?.map((e) => %s.values.firstWhere((element) => element.value == e)).toList()",
					key, enumName), nil
			case !attribute.Required:
				return fmt.Sprintf("%s.fromValue(map['%s'])", enumName, key), nil
			}

			return fmt.Sprintf("%s.values.firstWhere((e) => e.value == map['%s'])", enumName, key), nil
		}

		if attribute.Array {
			return fmt.Sprintf("List<String>.from(map['%s'] ?? [])", key), nil
		}

		optional := ""
		if !attribute.Required {
			optional = "?"
		}

		return fmt.Sprintf("map['%s']%s.toString()", key, optional), nil

	case attribute.Type == AttributeTypeInteger:
		if attribute.Array {
			return fmt.Sprintf("List<int>.from(map['%s'] ?? [])", key), nil
		}

		return fmt.Sprintf("map['%s']", key), nil

	case attribute.Type == AttributeTypeFloat:
		if attribute.Array {
			return fmt.Sprintf("List<double>.from(map['%s'] ?? [])", key), nil
		}

		return fmt.Sprintf("map['%s']", key), nil

	case attribute.Type == AttributeTypeBoolean:
		if attribute.Array {
			return fmt.Sprintf("List<bool>.from(map['%s'] ?? [])", key), nil
		}

		return fmt.Sprintf("map['%s']", key), nil

	case attribute.Type == AttributeTypeRelationship:
		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}
		relatedClass := ToPascalCase(related.Name)

		switch {
		case IsRelationshipList(attribute):
			return fmt.Sprintf(
				"(map['%s'] as List<dynamic>?)?.map((e) => %s.fromMap(e)).toList()", key, relatedClass), nil
		case !attribute.Required:
			return fmt.Sprintf("map['%s'] != null ? %s.fromMap(map['%s']) : null",
				key, relatedClass, key), nil
		}

		return fmt.Sprintf("%s.fromMap(map['%s'])", relatedClass, key), nil
	}

	// Geometry types match no branch and yield nothing at all.
	return "", nil
}

// toMapExpression builds one value of the toMap() literal.
func (d Dart) toMapExpression(attribute Attribute, name string) string {
	optional := ""
	if !attribute.Required {
		optional = "?"
	}

	switch {
	case attribute.Type == AttributeTypeRelationship:
		if IsRelationshipList(attribute) {
			return name + optional + ".map((e) => e.toMap()).toList()"
		}

		return name + optional + ".toMap()"

	case attribute.Format == AttributeTypeEnum:
		if attribute.Array {
			return name + optional + ".map((e) => e.value).toList()"
		}

		return name + optional + ".value"
	}

	return name
}
