package typegen

import (
	"fmt"
	"strings"
)

// JavaScript is not TypeScript with the types erased -- the two emitters differ
// in ways that are easy to assume away:
//
//   - enum names are toPascalCase(attribute.key) alone, so two collections with
//     a `status` enum both generate `Status` and the second silently wins
//   - point/linestring/polygon emit number[] rather than Array<number>
//   - the dependency choice is node-appwrite or appwrite only
//   - enum values are interpolated into JSDoc unescaped, so an element
//     containing a quote produces a malformed typedef
//
// All four are reproduced. They are the shipping behaviour, and `types` output
// is checked into users' repositories -- changing it here would show up as a
// diff in their project the first time they run the Go build.
type JavaScript struct {
	// Dependency is resolved by JavaScriptDependency().
	Dependency string
}

// Type implements Language. collections resolves relationships; collectionName
// is unused, because javascript.ts does not namespace its enums.
func (j JavaScript) Type(attribute Attribute, collections []Collection, _ string) (string, error) {
	var literal string

	switch attribute.Type {
	case AttributeTypeString, AttributeTypeText, AttributeTypeVarchar,
		AttributeTypeMediumText, AttributeTypeLongText, AttributeTypeDateTime:
		literal = "string"
		if attribute.Format == AttributeTypeEnum {
			literal = ToPascalCase(attribute.Key)
		}
	case AttributeTypeInteger, AttributeTypeFloat:
		literal = "number"
	case AttributeTypeBoolean:
		literal = "boolean"
	case AttributeTypeRelationship:
		// Note this is LanguageMeta.getRelatedCollection, which matches on $id
		// only -- unlike the TypeScript emitter's helper, which also matches on
		// name.
		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		literal = ToPascalCase(related.Name)
		if IsRelationshipList(attribute) {
			literal += "[]"
		}
	case AttributeTypePoint:
		literal = "number[]"
	case AttributeTypeLineString:
		literal = "number[][]"
	case AttributeTypePolygon:
		literal = "number[][][]"
	default:
		return "", &UnknownAttributeTypeError{Type: attribute.Type}
	}

	if attribute.Array {
		literal += "[]"
	}
	if attribute.Nullable() {
		literal += " | null"
	}

	return literal, nil
}

// SingleFile implements Language.
func (j JavaScript) SingleFile() bool { return true }

// FileName implements Language.
func (j JavaScript) FileName(*Collection) string { return "appwrite-types.js" }

// Render implements Language.
func (j JavaScript) Render(collections []Collection, _ *Collection, strict bool, invocation string) (string, error) {
	var out strings.Builder

	dependency := j.Dependency
	if dependency == "" {
		dependency = "appwrite"
	}

	out.WriteString("/**\n")
	fmt.Fprintf(&out, " * @typedef {import('%s').Models.Row} Row\n", dependency)
	out.WriteString(" */\n\n")
	out.WriteString("// This file is auto-generated by the Appwrite CLI.\n")
	fmt.Fprintf(&out, "// You can regenerate it by running `appwrite %s`.\n\n", invocation)

	for _, collection := range collections {
		for _, attribute := range collection.Attributes {
			if attribute.Format != AttributeTypeEnum {
				continue
			}

			// join('"|"') inside a quoted pair, with no escaping of the
			// elements themselves.
			out.WriteString("/**\n")
			fmt.Fprintf(&out, " * @typedef {\"%s\"} %s\n",
				strings.Join(attribute.Elements, `"|"`), ToPascalCase(attribute.Key))
			out.WriteString(" */\n\n")
		}
	}

	for index, collection := range collections {
		out.WriteString("/**\n * @typedef {Row & {\n")

		for _, attribute := range collection.Attributes {
			literal, err := j.Type(attribute, collections, collection.Name)
			if err != nil {
				return "", err
			}

			fmt.Fprintf(&out, " *   %s: %s;\n", PropertyName(attribute, strict), literal)
		}

		fmt.Fprintf(&out, " * }} %s\n */\n", ToPascalCase(collection.Name))
		if index < len(collections)-1 {
			out.WriteString("\n")
		}
	}

	return out.String(), nil
}
