package typegen

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/{{ sdk.gitUserName }}/{{ sdk.gitRepoName | caseDash }}/internal/jsonx"
)

// Ports templates/cli/lib/type-generation/languages/typescript.ts and the
// shared helper it delegates to, lib/shared/typescript-type-utils.ts.

// TypeScript emits an appwrite.d.ts.
type TypeScript struct {
	// Dependency is the package the generated file imports Models from,
	// resolved by AppwriteDependency().
	Dependency string
}

// identifierPattern decides whether a property key can be written bare or has
// to be quoted. `$` is legal in a JavaScript identifier, which is what makes
// `$id` and `$createdAt` emit without quotes.
var identifierPattern = regexp.MustCompile(`^[a-zA-Z_$][a-zA-Z0-9_$]*$`)

// Type implements Language.
func (t TypeScript) Type(attribute Attribute, collections []Collection, collectionName string) (string, error) {
	return typeScriptType(attribute, collections, collectionName, false)
}

// typeScriptType ports getTypeScriptType().
//
// forCreate is carried through for the databases generator, which emits input
// types where a relationship accepts either a nested create object or the id of
// an existing row.
func typeScriptType(attribute Attribute, collections []Collection, entityName string, forCreate bool) (string, error) {
	var literal string

	switch attribute.Type {
	case AttributeTypeString, AttributeTypeText, AttributeTypeVarchar,
		AttributeTypeMediumText, AttributeTypeLongText, AttributeTypeDateTime:
		literal = "string"
		if attribute.Format == AttributeTypeEnum {
			literal = ToPascalCase(entityName) + ToPascalCase(attribute.Key)
		}
	case AttributeTypeInteger, AttributeTypeFloat:
		literal = "number"
	case AttributeTypeBigInt:
		literal = "bigint"
	case AttributeTypeBoolean:
		literal = "boolean"
	case AttributeTypeRelationship:
		related, err := resolveRelated(attribute, collections)
		if err != nil {
			return "", err
		}

		base := ToPascalCase(related.Name)
		if forCreate {
			literal = fmt.Sprintf(
				"((%sCreate & { $id?: string; $permissions?: string[] }) | string)", base)
		} else {
			literal = base
		}

		if IsRelationshipList(attribute) {
			literal += "[]"
		}
	case AttributeTypePoint:
		literal = "Array<number>"
	case AttributeTypeLineString:
		literal = "Array<Array<number>>"
	case AttributeTypePolygon:
		literal = "Array<Array<Array<number>>>"
	default:
		return "", &UnknownAttributeTypeError{Type: attribute.Type}
	}

	if attribute.Array {
		literal += "[]"
	}
	if attribute.Nullable() {
		literal += " | null"
	}

	return literal, nil
}

// resolveRelated matches on $id or name.
//
// The wider lookup is deliberate and differs from LanguageMeta's id-only
// getRelatedCollection(): a config hand-edited to reference a collection by
// name still resolves here. Reproduced rather than unified, because the two
// TypeScript helpers really do behave differently and the languages that use
// each one must keep matching their own.
func resolveRelated(attribute Attribute, collections []Collection) (Collection, error) {
	id := RelatedCollectionID(attribute)
	for _, collection := range collections {
		if collection.ID == id || collection.Name == id {
			return collection, nil
		}
	}

	return Collection{}, fmt.Errorf("related entity with ID '%s' not found", id)
}

// CreateType is the type literal for an input position.
//
// Used by `generate`, not by `types`: in a create payload a relationship
// accepts either a nested create object or the id of an existing row, so it
// widens to `((XCreate & { $id?: string; ... }) | string)`.
func (t TypeScript) CreateType(attribute Attribute, collections []Collection, entityName string) (string, error) {
	return typeScriptType(attribute, collections, entityName, true)
}

// SingleFile implements Language.
func (t TypeScript) SingleFile() bool { return true }

// FileName implements Language.
func (t TypeScript) FileName(*Collection) string { return "appwrite.d.ts" }

// Enum builds the enum for one attribute.
func (t TypeScript) Enum(entityName, attributeKey string, elements []string) EnumDefinition {
	return EnumDefinition{
		Name:    ToPascalCase(entityName) + ToPascalCase(attributeKey),
		Members: generateEnumMembers(elements),
	}
}

// Render implements Language.
//
// Layout is pinned to the EJS template's output, including the blank line after
// each enum and the blank line between collections but not after the last.
func (t TypeScript) Render(collections []Collection, _ *Collection, strict bool, invocation string) (string, error) {
	var out strings.Builder

	dependency := t.Dependency
	if dependency == "" {
		dependency = "appwrite"
	}

	fmt.Fprintf(&out, "import type { Models } from '%s';\n\n", dependency)
	out.WriteString("// This file is auto-generated by the Appwrite CLI.\n")
	fmt.Fprintf(&out, "// You can regenerate it by running `appwrite %s`.\n\n", invocation)

	for _, collection := range collections {
		for _, attribute := range collection.Attributes {
			if attribute.Format != AttributeTypeEnum {
				continue
			}

			definition := t.Enum(collection.Name, attribute.Key, attribute.Elements)
			fmt.Fprintf(&out, "export enum %s {\n", definition.Name)

			for index, member := range definition.Members {
				value, err := jsonx.Marshal(member.Value)
				if err != nil {
					return "", err
				}

				separator := ""
				if index < len(definition.Members)-1 {
					separator = ","
				}
				fmt.Fprintf(&out, "    %s = %s%s\n", member.Key, value, separator)
			}

			out.WriteString("}\n\n")
		}
	}

	for index, collection := range collections {
		fmt.Fprintf(&out, "export type %s = Models.Row & {\n", ToPascalCase(collection.Name))

		for _, attribute := range collection.Attributes {
			literal, err := t.Type(attribute, collections, collection.Name)
			if err != nil {
				return "", err
			}

			property := PropertyName(attribute, strict)
			if !identifierPattern.MatchString(property) {
				property = `"` + property + `"`
			}

			fmt.Fprintf(&out, "    %s: %s;\n", property, literal)
		}

		out.WriteString("}\n")
		if index < len(collections)-1 {
			out.WriteString("\n")
		}
	}

	return out.String(), nil
}
