name: Analyze and test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
      - name: Install dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze --no-fatal-warnings
      - name: Test
        run: dart test
