/// This file is auto-generated by the Appwrite CLI. 
/// You can regenerate it by running `appwrite types ./types`.

#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;

namespace Appwrite.Models
{

public enum AuthorsStatus {
    [JsonPropertyName("active")]
    Active,
    [JsonPropertyName("in-active")]
    InActive,
    [JsonPropertyName("in active")]
    InActive,
    [JsonPropertyName("9lives")]
    9lives,
    [JsonPropertyName("in_active")]
    InActive
}

public class Authors
{
    [JsonPropertyName("$id")]
    public string Id { get; private set; }

    [JsonPropertyName("full name")]
    public string FullName { get; private set; }

    [JsonPropertyName("bio")]
    public string? Bio { get; private set; }

    [JsonPropertyName("age")]
    public long? Age { get; private set; }

    [JsonPropertyName("rating")]
    public double Rating { get; private set; }

    [JsonPropertyName("verified")]
    public bool? Verified { get; private set; }

    [JsonPropertyName("joined-at")]
    public string JoinedAt { get; private set; }

    [JsonPropertyName("tags")]
    public List<string>? Tags { get; private set; }

    [JsonPropertyName("status")]
    public AuthorsStatus Status { get; private set; }

    [JsonPropertyName("books")]
    public List<BooksZines>? Books { get; private set; }

    [JsonPropertyName("home")]
    public List<double>? Home { get; private set; }

    [JsonPropertyName("route")]
    public List<List<double>> Route { get; private set; }

    [JsonPropertyName("region")]
    public List<List<List<double>>> Region { get; private set; }

    [JsonPropertyName("weird key!")]
    public string WeirdKey { get; private set; }


    public Authors(
        string id,
        string fullName,
        string? bio,
        long? age,
        double rating,
        bool? verified,
        string joinedAt,
        List<string>? tags,
        AuthorsStatus status,
        List<BooksZines>? books,
        List<double>? home,
        List<List<double>> route,
        List<List<List<double>>> region,
        string weirdKey
    )
    {
        Id = id;
        FullName = fullName;
        Bio = bio;
        Age = age;
        Rating = rating;
        Verified = verified;
        JoinedAt = joinedAt;
        Tags = tags;
        Status = status;
        Books = books;
        Home = home;
        Route = route;
        Region = region;
        WeirdKey = weirdKey;
    }

    public static Authors From(Dictionary<string, object> map) => new Authors(
        id: map["$id"].ToString()!,
        fullName: map["full name"].ToString()!,
        bio: map["bio"]?.ToString(),
        age: map["age"] == null ? null : Convert.ToInt64(map["age"]),
        rating: Convert.ToDouble(map["rating"]),
        verified: (bool?)map["verified"],
        joinedAt: map["joined-at"].ToString()!,
        tags: ((IEnumerable<object>)map["tags"]).Select(x => x?.ToString()).ToList()!,
        status: Enum.Parse<Models.AuthorsStatus>(map["status"].ToString()!, true),
        books: ((IEnumerable<object>)map["books"]).Select(it => Models.BooksZines.From((Dictionary<string, object>)it)).ToList(),
        home: default,
        route: default,
        region: default,
        weirdKey: map["weird key!"].ToString()!
    );

    public Dictionary<string, object?> ToMap() => new Dictionary<string, object?>()
    {
        { "$id", Id },
        { "full name", FullName },
        { "bio", Bio },
        { "age", Age },
        { "rating", Rating },
        { "verified", Verified },
        { "joined-at", JoinedAt },
        { "tags", Tags },
        { "status", Status?.ToString() },
        { "books", Books?.Select(e => e.ToMap()).ToList() },
        { "home", Home },
        { "route", Route },
        { "region", Region },
        { "weird key!", WeirdKey }
    };
}
}
