/// This file is auto-generated by the Appwrite CLI. 
/// You can regenerate it by running `appwrite types ./types`.

#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;

namespace Appwrite.Models
{

public enum BooksZinesKind {
    [JsonPropertyName("hard<cover>")]
    Hardcover,
    [JsonPropertyName("soft"cover"")]
    Softcover,
    [JsonPropertyName("")]
    
}

public class BooksZines
{
    [JsonPropertyName("title")]
    public string Title { get; private set; }

    [JsonPropertyName("author")]
    public List<Authors> Author { get; private set; }

    [JsonPropertyName("r&d<flag>")]
    public string Rdflag { get; private set; }

    [JsonPropertyName("kind")]
    public BooksZinesKind Kind { get; private set; }


    public BooksZines(
        string title,
        List<Authors> author,
        string rdflag,
        BooksZinesKind kind
    )
    {
        Title = title;
        Author = author;
        Rdflag = rdflag;
        Kind = kind;
    }

    public static BooksZines From(Dictionary<string, object> map) => new BooksZines(
        title: map["title"].ToString()!,
        author: ((IEnumerable<object>)map["author"]).Select(it => Models.Authors.From((Dictionary<string, object>)it)).ToList(),
        rdflag: map["r&d<flag>"].ToString()!,
        kind: Enum.Parse<Models.BooksZinesKind>(map["kind"].ToString()!, true)
    );

    public Dictionary<string, object?> ToMap() => new Dictionary<string, object?>()
    {
        { "title", Title },
        { "author", Author?.Select(e => e.ToMap()).ToList() },
        { "r&d<flag>", Rdflag },
        { "kind", Kind?.ToString() }
    };
}
}
