// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types ./types`.
import 'books_zines.dart';

enum AuthorsStatus {
  ACTIVE("active"),
  IN_ACTIVE("in-active"),
  IN_ACTIVE_1("in active"),
  _9LIVES("9lives"),
  IN_ACTIVE_2("in_active");

  const AuthorsStatus(this.value);
  final String value;

  static AuthorsStatus? fromValue(String? value) {
    if (value == null) return null;
    return AuthorsStatus.values.firstWhere((element) => element.value == value);
  }
}

class Authors {
  String $id;
  String full name;
  double rating;
  String joined-at;
  AuthorsStatus status;
  List<List<double>> route;
  List<List<List<double>>> region;
  String weird key!;
  String? bio;
  int? age;
  bool? verified;
  List<String>? tags;
  List<BooksZines>? books;
  List<double>? home;

  Authors({
    required this.$id,
    required this.full name,
    required this.rating,
    required this.joined-at,
    required this.status,
    required this.route,
    required this.region,
    required this.weird key!,
    this.bio,
    this.age,
    this.verified,
    this.tags,
    this.books,
    this.home
  });

  factory Authors.fromMap(Map<String, dynamic> map) {
    return Authors(
      $id: map['$id'].toString(),
      full name: map['full name'].toString(),
      rating: map['rating'],
      joined-at: map['joined-at'].toString(),
      status: AuthorsStatus.values.firstWhere((e) => e.value == map['status']),
      route: ,
      region: ,
      weird key!: map['weird key!'].toString(),
      bio: map['bio']?.toString(),
      age: map['age'],
      verified: map['verified'],
      tags: List<String>.from(map['tags'] ?? []),
      books: (map['books'] as List<dynamic>?)?.map((e) => BooksZines.fromMap(e)).toList(),
      home: 
    );
  }

  Map<String, dynamic> toMap() {
    return {
      '$id': $id,
      'full name': full name,
      'rating': rating,
      'joined-at': joined-at,
      'status': status.value,
      'route': route,
      'region': region,
      'weird key!': weird key!,
      'bio': bio,
      'age': age,
      'verified': verified,
      'tags': tags,
      'books': books?.map((e) => e.toMap()).toList(),
      'home': home
    };
  }
}
