// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types ./types`.
import 'authors.dart';

enum BooksZinesKind {
  HARDCOVER("hard<cover>"),
  SOFTCOVER("soft"cover""),
  _("");

  const BooksZinesKind(this.value);
  final String value;

  static BooksZinesKind? fromValue(String? value) {
    if (value == null) return null;
    return BooksZinesKind.values.firstWhere((element) => element.value == value);
  }
}

class BooksZines {
  String title;
  List<Authors> author;
  String rdflag;
  BooksZinesKind kind;

  BooksZines({
    required this.title,
    required this.author,
    required this.rdflag,
    required this.kind
  });

  factory BooksZines.fromMap(Map<String, dynamic> map) {
    return BooksZines(
      title: map['title'].toString(),
      author: (map['author'] as List<dynamic>?)?.map((e) => Authors.fromMap(e)).toList(),
      rdflag: map['r&amp;d&lt;flag&gt;'].toString(),
      kind: BooksZinesKind.values.firstWhere((e) => e.value == map['kind'])
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'author': author.map((e) => e.toMap()).toList(),
      'r&amp;d&lt;flag&gt;': rdflag,
      'kind': kind.value
    };
  }
}
