package io.appwrite.models;

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types ./types`.
 */

import java.util.Objects;
import io.appwrite.models.BooksZines;

public class Authors {

    public enum AuthorsStatus {
        active,
        in-active,
        in active,
        9lives,
        in_active;
    }

    private String $id;
    private String full name;
    private String bio;
    private Integer age;
    private Double rating;
    private Boolean verified;
    private String joined-at;
    private List<String> tags;
    private AuthorsStatus status;
    private List<BooksZines> books;
    private List<Double> home;
    private List<List<Double>> route;
    private List<List<List<Double>>> region;
    private String weird key!;

    public Authors() {
    }

    public Authors(
        String $id,
        String full name,
        String bio,
        Integer age,
        Double rating,
        Boolean verified,
        String joined-at,
        List<String> tags,
        AuthorsStatus status,
        List<BooksZines> books,
        List<Double> home,
        List<List<Double>> route,
        List<List<List<Double>>> region,
        String weird key!
    ) {
        this.$id = $id;
        this.full name = full name;
        this.bio = bio;
        this.age = age;
        this.rating = rating;
        this.verified = verified;
        this.joined-at = joined-at;
        this.tags = tags;
        this.status = status;
        this.books = books;
        this.home = home;
        this.route = route;
        this.region = region;
        this.weird key! = weird key!;
    }

    public String getId() {
        return $id;
    }

    public void setId(String $id) {
        this.$id = $id;
    }

    public String getFullName() {
        return full name;
    }

    public void setFullName(String full name) {
        this.full name = full name;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Double getRating() {
        return rating;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    public Boolean getVerified() {
        return verified;
    }

    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    public String getJoinedAt() {
        return joined-at;
    }

    public void setJoinedAt(String joined-at) {
        this.joined-at = joined-at;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public AuthorsStatus getStatus() {
        return status;
    }

    public void setStatus(AuthorsStatus status) {
        this.status = status;
    }

    public List<BooksZines> getBooks() {
        return books;
    }

    public void setBooks(List<BooksZines> books) {
        this.books = books;
    }

    public List<Double> getHome() {
        return home;
    }

    public void setHome(List<Double> home) {
        this.home = home;
    }

    public List<List<Double>> getRoute() {
        return route;
    }

    public void setRoute(List<List<Double>> route) {
        this.route = route;
    }

    public List<List<List<Double>>> getRegion() {
        return region;
    }

    public void setRegion(List<List<List<Double>>> region) {
        this.region = region;
    }

    public String getWeirdKey() {
        return weird key!;
    }

    public void setWeirdKey(String weird key!) {
        this.weird key! = weird key!;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        Authors that = (Authors) obj;
        return Objects.equals(id, that.id) &&
          Objects.equals(fullName, that.fullName) &&
          Objects.equals(bio, that.bio) &&
          Objects.equals(age, that.age) &&
          Objects.equals(rating, that.rating) &&
          Objects.equals(verified, that.verified) &&
          Objects.equals(joinedAt, that.joinedAt) &&
          Objects.equals(tags, that.tags) &&
          Objects.equals(status, that.status) &&
          Objects.equals(books, that.books) &&
          Objects.equals(home, that.home) &&
          Objects.equals(route, that.route) &&
          Objects.equals(region, that.region) &&
          Objects.equals(weirdKey, that.weirdKey);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, fullName, bio, age, rating, verified, joinedAt, tags, status, books, home, route, region, weirdKey);
    }

    @Override
    public String toString() {
        return "Authors{" +
                "$id=" + $id + ", " +
                "full name=" + full name + ", " +
                "bio=" + bio + ", " +
                "age=" + age + ", " +
                "rating=" + rating + ", " +
                "verified=" + verified + ", " +
                "joined-at=" + joined-at + ", " +
                "tags=" + tags + ", " +
                "status=" + status + ", " +
                "books=" + books + ", " +
                "home=" + home + ", " +
                "route=" + route + ", " +
                "region=" + region + ", " +
                "weird key!=" + weird key! +
                '}';
    }
}
