package io.appwrite.models

import Authors

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types ./types`.
 */

enum class BooksZinesKind {
    HARDCOVER,
    SOFTCOVER,
    
}

data class BooksZines(
    val title: String,
    val author: List<Authors>,
    val rdflag: String,
    val kind: BooksZinesKind
)
