package io.appwrite.models

import BooksZines

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types ./types`.
 */

enum class AuthorsStatus {
    active,
    in-active,
    in active,
    9lives,
    in_active
}

data class Authors(
    val $id: String,
    val full name: String,
    val bio: String?,
    val age: Long?,
    val rating: Float,
    val verified: Boolean?,
    val joined-at: String,
    val tags: List<String>?,
    val status: AuthorsStatus,
    val books: List<BooksZines>?,
    val home: List<Double>?,
    val route: List<List<Double>>,
    val region: List<List<List<Double>>>,
    val weird key!: String
)
