package io.appwrite.models

import Authors

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types ./types`.
 */

enum class BooksZinesKind {
    hard<cover>,
    soft"cover",
    
}

data class BooksZines(
    val title: String,
    val author: List<Authors>,
    val r&d<flag>: String,
    val kind: BooksZinesKind
)
