<?php
namespace Appwrite\Models;

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types ./types`.

use Appwrite\Models\Authors;

enum BooksZinesKind: string {
    case HARDCOVER = 'hard<cover>';
    case SOFTCOVER = 'soft"cover"';
    case  = '';
}

class BooksZines {
    private string $title;
    private array $author;
    private string $rdflag;
    private BooksZinesKind $kind;

    public function __construct(
        string $title,
        array $author,
        string $rdflag,
        BooksZinesKind $kind
    ) {
        $this->title = $title;
        $this->author = $author;
        $this->rdflag = $rdflag;
        $this->kind = $kind;
    }

    public function getTitle(): string {
        return $this->title;
    }

    public function setTitle(string $title): void {
        $this->title = $title;
    }

    public function getAuthor(): array {
        return $this->author;
    }

    public function setAuthor(array $author): void {
        $this->author = $author;
    }

    public function getRdflag(): string {
        return $this->rdflag;
    }

    public function setRdflag(string $rdflag): void {
        $this->rdflag = $rdflag;
    }

    public function getKind(): BooksZinesKind {
        return $this->kind;
    }

    public function setKind(BooksZinesKind $kind): void {
        $this->kind = $kind;
    }
}
