import Foundation

/// This file is auto-generated by the Appwrite CLI. 
/// You can regenerate it by running `appwrite types ./types`.

public enum AuthorsStatus: String, Codable, CaseIterable {
    case active = "active"
    case in-active = "in-active"
    case in active = "in active"
    case 9lives = "9lives"
    case in_active = "in_active"
}

public class Authors: Codable {
    public let $id: String
    public let full name: String
    public let bio: String?
    public let age: Int?
    public let rating: Double
    public let verified: Bool?
    public let joined-at: String
    public let tags: [String]?
    public let status: AuthorsStatus
    public let books: [BooksZines]?
    public let home: [Double]?
    public let route: [[Double]]
    public let region: [[[Double]]]
    public let weird key!: String

    enum CodingKeys: String, CodingKey {
        case $id = "$id"
        case full name = "full name"
        case bio = "bio"
        case age = "age"
        case rating = "rating"
        case verified = "verified"
        case joined-at = "joined-at"
        case tags = "tags"
        case status = "status"
        case books = "books"
        case home = "home"
        case route = "route"
        case region = "region"
        case weird key! = "weird key!"
    }

    public init(
        $id: String,
        full name: String,
        bio: String?,
        age: Int?,
        rating: Double,
        verified: Bool?,
        joined-at: String,
        tags: [String]?,
        status: AuthorsStatus,
        books: [BooksZines]?,
        home: [Double]?,
        route: [[Double]],
        region: [[[Double]]],
        weird key!: String
    ) {
        self.$id = $id
        self.full name = full name
        self.bio = bio
        self.age = age
        self.rating = rating
        self.verified = verified
        self.joined-at = joined-at
        self.tags = tags
        self.status = status
        self.books = books
        self.home = home
        self.route = route
        self.region = region
        self.weird key! = weird key!
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.$id = try container.decode(String.self, forKey: .$id)
        self.full name = try container.decode(String.self, forKey: .full name)
        self.bio = try container.decodeIfPresent(String.self, forKey: .bio)
        self.age = try container.decodeIfPresent(Int.self, forKey: .age)
        self.rating = try container.decode(Double.self, forKey: .rating)
        self.verified = try container.decodeIfPresent(Bool.self, forKey: .verified)
        self.joined-at = try container.decode(String.self, forKey: .joined-at)
        self.tags = try container.decodeIfPresent([String].self, forKey: .tags)
        self.status = try container.decode(AuthorsStatus.self, forKey: .status)
        self.books = try container.decodeIfPresent([BooksZines].self, forKey: .books)
        self.home = try container.decodeIfPresent([Double].self, forKey: .home)
        self.route = try container.decode([[Double]].self, forKey: .route)
        self.region = try container.decode([[[Double]]].self, forKey: .region)
        self.weird key! = try container.decode(String.self, forKey: .weird key!)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode($id, forKey: .$id)
        try container.encode(full name, forKey: .full name)
        try container.encodeIfPresent(bio, forKey: .bio)
        try container.encodeIfPresent(age, forKey: .age)
        try container.encode(rating, forKey: .rating)
        try container.encodeIfPresent(verified, forKey: .verified)
        try container.encode(joined-at, forKey: .joined-at)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(books, forKey: .books)
        try container.encodeIfPresent(home, forKey: .home)
        try container.encode(route, forKey: .route)
        try container.encode(region, forKey: .region)
        try container.encode(weird key!, forKey: .weird key!)
    }

    public func toMap() -> [String: Any] {
        return [
            "$id": $id as Any,
            "full name": full name as Any,
            "bio": bio as Any,
            "age": age as Any,
            "rating": rating as Any,
            "verified": verified as Any,
            "joined-at": joined-at as Any,
            "tags": tags as Any,
            "status": status as Any,
            "books": books as Any,
            "home": home as Any,
            "route": route as Any,
            "region": region as Any,
            "weird key!": weird key! as Any
        ]
    }

    public static func from(map: [String: Any]) -> Authors {
        return Authors(
            $id: map["$id"] as! String,
            full name: map["full name"] as! String,
            bio: map["bio"] as? String,
            age: map["age"] as? Int,
            rating: Double.from(map: map["rating"] as! [String: Any]),
            verified: map["verified"] as? Bool,
            joined-at: map["joined-at"] as! String,
            tags: map["tags"] as? [String],
            status: AuthorsStatus(rawValue: map["status"] as! String)!,
            books: map["books"] as? [BooksZines],
            home: Point.from(map: map["home"] as! [String: Any]),
            route: Linestring.from(map: map["route"] as! [String: Any]),
            region: Polygon.from(map: map["region"] as! [String: Any]),
            weird key!: map["weird key!"] as! String
        )
    }
}