import Foundation

/// This file is auto-generated by the Appwrite CLI. 
/// You can regenerate it by running `appwrite types ./types`.

public enum BooksZinesKind: String, Codable, CaseIterable {
    case hard<cover> = "hard<cover>"
    case soft"cover" = "soft"cover""
    case  = ""
}

public class BooksZines: Codable {
    public let title: String
    public let author: [Authors]
    public let r&d<flag>: String
    public let kind: BooksZinesKind

    enum CodingKeys: String, CodingKey {
        case title = "title"
        case author = "author"
        case r&d<flag> = "r&d<flag>"
        case kind = "kind"
    }

    public init(
        title: String,
        author: [Authors],
        r&d<flag>: String,
        kind: BooksZinesKind
    ) {
        self.title = title
        self.author = author
        self.r&d<flag> = r&d<flag>
        self.kind = kind
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.title = try container.decode(String.self, forKey: .title)
        self.author = try container.decode([Authors].self, forKey: .author)
        self.r&d<flag> = try container.decode(String.self, forKey: .r&d<flag>)
        self.kind = try container.decode(BooksZinesKind.self, forKey: .kind)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encode(title, forKey: .title)
        try container.encode(author, forKey: .author)
        try container.encode(r&d<flag>, forKey: .r&d<flag>)
        try container.encode(kind, forKey: .kind)
    }

    public func toMap() -> [String: Any] {
        return [
            "title": title as Any,
            "author": author as Any,
            "r&d<flag>": r&d<flag> as Any,
            "kind": kind as Any
        ]
    }

    public static func from(map: [String: Any]) -> BooksZines {
        return BooksZines(
            title: map["title"] as! String,
            author: map["author"] as! [Authors],
            r&d<flag>: map["r&d<flag>"] as! String,
            kind: BooksZinesKind(rawValue: map["kind"] as! String)!
        )
    }
}