import type { Models } from '@appwrite.io/console';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types ./types`.

export enum AuthorsStatus {
    ACTIVE = "active",
    IN_ACTIVE = "in-active",
    IN_ACTIVE_1 = "in active",
    _9LIVES = "9lives",
    IN_ACTIVE_2 = "in_active"
}

export enum BooksZinesKind {
    HARDCOVER = "hard<cover>",
    SOFTCOVER = "soft\"cover\"",
    _ = ""
}

export type Authors = Models.Row & {
    id: string;
    fullName: string;
    bio: string | null;
    age: number | null;
    rating: number;
    verified: boolean | null;
    joinedAt: string;
    tags: string[] | null;
    status: AuthorsStatus;
    books: BooksZines[] | null;
    home: Array<number> | null;
    route: Array<Array<number>>;
    region: Array<Array<Array<number>>>;
    weirdKey: string;
}

export type BooksZines = Models.Row & {
    title: string;
    author: Authors[];
    rdflag: string;
    kind: BooksZinesKind;
}
