
## Contributing

This library is auto-generated by Appwrite custom [SDK Generator](https://github.com/appwrite/sdk-generator). To learn more about how you can help us improve this SDK, please check the [contribution guide](https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md) before sending a pull-request.

To build and test the CLI for development, follow these steps 

1. Clone the SDK Generator
```sh
$ git clone https://github.com/appwrite/sdk-generator
```

2. Ensure that docker is running locally and then run 
```sh 
$ cd sdk-generator

# Install the composer dependencies
$ docker run --rm --interactive --tty --volume "$(pwd)":/app composer install --ignore-platform-reqs --optimize-autoloader --no-plugins --no-scripts --prefer-dist

# Generate the SDKs
$ docker run --rm -v $(pwd):/app -w /app php:7.4-cli php example.php
```

3. Head over to the generated SDK and build the CLI docker image 
```sh
$ cd examples/CLI
$ docker build -t appwrite/cli .
```

4. Install the CLI

MacOS and Linux

Open `install.sh` and change [this line](https://github.com/appwrite/sdk-for-cli/blob/master/install.sh#L33) to `APPWRITE_CLI_IMAGE_VERSION=latest` and 
comment [these lines](https://github.com/appwrite/sdk-for-cli/blob/master/install.sh#L119-L123). 

You can now install the CLI using 
```sh
$ chmod +x install.sh
$ ./install.sh
```

Windows

Open `install.ps1` and change [this line](https://github.com/appwrite/sdk-for-cli/blob/master/install.ps1#L28) to `APPWRITE_CLI_IMAGE_VERSION=latest` and 
comment [these lines](https://github.com/appwrite/sdk-for-cli/blob/master/install.ps1#L85-L89)

You can now install the CLI using 
```sh
$ ./install.ps1
```