language: swift
osx_image: xcode12.5
before_install:
  - gem install cocoapods
  - pod install

jobs:
  include:
    - stage: Pod Lint
      script:
        - pod lib lint --allow-warnings
      on:
        tags: true