package typegen

import (
	"fmt"
	"strings"
)

// The Java template mixes EJS's two interpolation forms for the same value:
// `<%- %>` writes the field declaration, `<%= %>` writes the constructor
// parameter, the assignment and toString(). An attribute key containing `&` or
// `<` therefore appears twice in one generated file, spelled two different
// ways. See EscapeXML.
//
// Java also drops nullability entirely -- getType() has no optional branch, so
// every field is the bare boxed type.
type Java struct{}

// Type implements Language.
func (j Java) Type(attribute Attribute, collections []Collection, collectionName string) (string, error) {
	var literal string

	switch attribute.Type {
	case AttributeTypeString, AttributeTypeText, AttributeTypeVarchar,
		AttributeTypeMediumText, AttributeTypeLongText, AttributeTypeDateTime:
		literal = "String"
		if attribute.Format == AttributeTypeEnum {
			literal = ToPascalCase(collectionName) + ToPascalCase(attribute.Key)
		}
	case AttributeTypeInteger:
		literal = "Integer"
	case AttributeTypeFloat:
		literal = "Double"
	case AttributeTypeBoolean:
		literal = "Boolean"
	case AttributeTypeRelationship:
		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		literal = ToPascalCase(related.Name)
		if IsRelationshipList(attribute) {
			literal = "List<" + literal + ">"
		}
	case AttributeTypePoint:
		literal = "List<Double>"
	case AttributeTypeLineString:
		literal = "List<List<Double>>"
	case AttributeTypePolygon:
		literal = "List<List<List<Double>>>"
	default:
		return "", &UnknownAttributeTypeError{Type: attribute.Type}
	}

	if attribute.Array {
		literal = "List<" + literal + ">"
	}

	// No nullable branch: java.ts returns here.
	return literal, nil
}

// SingleFile implements Language.
func (j Java) SingleFile() bool { return false }

// FileName implements Language.
func (j Java) FileName(collection *Collection) string {
	return ToPascalCase(collection.Name) + ".java"
}

// Render implements Language.
func (j Java) Render(collections []Collection, current *Collection, strict bool, invocation string) (string, error) {
	var out strings.Builder

	out.WriteString("package io.appwrite.models;\n\n")
	// The trailing space after "CLI." is in the template.
	out.WriteString("/**\n * This file is auto-generated by the Appwrite CLI. \n")
	fmt.Fprintf(&out, " * You can regenerate it by running `appwrite %s`.\n */\n\n", invocation)
	out.WriteString("import java.util.Objects;\n")

	for _, attribute := range current.Attributes {
		if attribute.Type != AttributeTypeRelationship {
			continue
		}

		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		fmt.Fprintf(&out, "import io.appwrite.models.%s;\n", ToPascalCase(related.Name))
	}

	className := ToPascalCase(current.Name)
	fmt.Fprintf(&out, "\npublic class %s {\n", className)

	for _, attribute := range current.Attributes {
		if attribute.Format != AttributeTypeEnum {
			continue
		}

		fmt.Fprintf(&out, "\n    public enum %s%s {\n", className, ToPascalCase(attribute.Key))
		for index, element := range attribute.Elements {
			entry := element
			if strict {
				entry = ToUpperSnakeCase(element)
			}

			// A semicolon rather than nothing after the last entry.
			terminator := ";"
			if index < len(attribute.Elements)-1 {
				terminator = ","
			}
			fmt.Fprintf(&out, "        %s%s\n", entry, terminator)
		}
		out.WriteString("    }\n\n")
	}

	types := make([]string, len(current.Attributes))
	names := make([]string, len(current.Attributes))
	camels := make([]string, len(current.Attributes))
	for index, attribute := range current.Attributes {
		literal, err := j.Type(attribute, collections, current.Name)
		if err != nil {
			return "", err
		}
		types[index] = literal
		names[index] = PropertyName(attribute, strict)
		// equals() and hashCode() always camelCase, regardless of --strict.
		camels[index] = ToCamelCase(attribute.Key)

		fmt.Fprintf(&out, "    private %s %s;\n", literal, names[index])
	}

	fmt.Fprintf(&out, "\n    public %s() {\n    }\n\n", className)

	fmt.Fprintf(&out, "    public %s(\n", className)
	for index := range current.Attributes {
		separator := ""
		if index < len(current.Attributes)-1 {
			separator = ","
		}
		fmt.Fprintf(&out, "        %s %s%s\n", types[index], EscapeXML(names[index]), separator)
	}
	out.WriteString("    ) {\n")
	for index := range current.Attributes {
		escaped := EscapeXML(names[index])
		fmt.Fprintf(&out, "        this.%s = %s;\n", escaped, escaped)
	}
	out.WriteString("    }\n\n")

	for index, attribute := range current.Attributes {
		accessor := ToPascalCase(attribute.Key)
		escaped := EscapeXML(names[index])

		fmt.Fprintf(&out, "    public %s get%s() {\n", types[index], accessor)
		fmt.Fprintf(&out, "        return %s;\n    }\n\n", escaped)
		fmt.Fprintf(&out, "    public void set%s(%s %s) {\n", accessor, types[index], escaped)
		fmt.Fprintf(&out, "        this.%s = %s;\n    }\n\n", escaped, escaped)
	}

	out.WriteString("    @Override\n    public boolean equals(Object obj) {\n")
	out.WriteString("        if (this == obj) return true;\n")
	out.WriteString("        if (obj == null || getClass() != obj.getClass()) return false;\n")
	fmt.Fprintf(&out, "        %s that = (%s) obj;\n", className, className)

	comparisons := make([]string, len(camels))
	for index, camel := range camels {
		comparisons[index] = fmt.Sprintf("Objects.equals(%s, that.%s)", camel, camel)
	}
	fmt.Fprintf(&out, "        return %s;\n    }\n\n", strings.Join(comparisons, " &&\n          "))

	out.WriteString("    @Override\n    public int hashCode() {\n")
	fmt.Fprintf(&out, "        return Objects.hash(%s);\n    }\n\n", strings.Join(camels, ", "))

	out.WriteString("    @Override\n    public String toString() {\n")
	fmt.Fprintf(&out, "        return \"%s{\" +\n", className)
	for index := range current.Attributes {
		escaped := EscapeXML(names[index])

		trailer := ""
		if index < len(current.Attributes)-1 {
			trailer = ` ", " +`
		}
		fmt.Fprintf(&out, "                \"%s=\" + %s +%s\n", escaped, escaped, trailer)
	}
	out.WriteString("                '}';\n    }\n}\n")

	return out.String(), nil
}
