package typegen

import (
	"fmt"
	"strings"
)

// Two things differ from the PHP emitter in ways worth stating, because they
// read as if they should match:
//
//   - the import loop has no filter, so a to-many relationship imports the
//     related class even though the field is a List of it
//   - enum entries are only normalised under --strict; without it the raw
//     element is emitted, which is invalid Kotlin for anything containing a
//     space or hyphen
type Kotlin struct{}

// Type implements Language.
func (k Kotlin) Type(attribute Attribute, collections []Collection, collectionName string) (string, error) {
	var literal string

	switch attribute.Type {
	case AttributeTypeString, AttributeTypeText, AttributeTypeVarchar,
		AttributeTypeMediumText, AttributeTypeLongText, AttributeTypeDateTime:
		literal = "String"
		if attribute.Format == AttributeTypeEnum {
			literal = ToPascalCase(collectionName) + ToPascalCase(attribute.Key)
		}
	case AttributeTypeInteger:
		literal = "Long"
	case AttributeTypeFloat:
		literal = "Float"
	case AttributeTypeBoolean:
		literal = "Boolean"
	case AttributeTypeRelationship:
		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		literal = ToPascalCase(related.Name)
		if IsRelationshipList(attribute) {
			literal = "List<" + literal + ">"
		}
	case AttributeTypePoint:
		literal = "List<Double>"
	case AttributeTypeLineString:
		literal = "List<List<Double>>"
	case AttributeTypePolygon:
		literal = "List<List<List<Double>>>"
	default:
		return "", &UnknownAttributeTypeError{Type: attribute.Type}
	}

	if attribute.Array {
		literal = "List<" + literal + ">"
	}
	if attribute.Nullable() {
		literal += "?"
	}

	return literal, nil
}

// SingleFile implements Language.
func (k Kotlin) SingleFile() bool { return false }

// FileName implements Language.
func (k Kotlin) FileName(collection *Collection) string {
	return ToPascalCase(collection.Name) + ".kt"
}

// Render implements Language.
func (k Kotlin) Render(collections []Collection, current *Collection, strict bool, invocation string) (string, error) {
	var out strings.Builder

	out.WriteString("package io.appwrite.models\n\n")

	for _, attribute := range current.Attributes {
		if attribute.Type != AttributeTypeRelationship {
			continue
		}

		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		fmt.Fprintf(&out, "import %s\n\n", ToPascalCase(related.Name))
	}

	// The trailing space after "CLI." is in the template.
	out.WriteString("/**\n * This file is auto-generated by the Appwrite CLI. \n")
	fmt.Fprintf(&out, " * You can regenerate it by running `appwrite %s`.\n */\n\n", invocation)

	for _, attribute := range current.Attributes {
		if attribute.Format != AttributeTypeEnum {
			continue
		}

		fmt.Fprintf(&out, "enum class %s%s {\n",
			ToPascalCase(current.Name), ToPascalCase(attribute.Key))
		for index, element := range attribute.Elements {
			entry := element
			if strict {
				entry = ToUpperSnakeCase(element)
			}

			separator := ""
			if index < len(attribute.Elements)-1 {
				separator = ","
			}
			fmt.Fprintf(&out, "    %s%s\n", entry, separator)
		}
		out.WriteString("}\n\n")
	}

	fmt.Fprintf(&out, "data class %s(\n", ToPascalCase(current.Name))
	for index, attribute := range current.Attributes {
		literal, err := k.Type(attribute, collections, current.Name)
		if err != nil {
			return "", err
		}

		separator := ""
		if index < len(current.Attributes)-1 {
			separator = ","
		}
		fmt.Fprintf(&out, "    val %s: %s%s\n", PropertyName(attribute, strict), literal, separator)
	}
	out.WriteString(")\n")

	return out.String(), nil
}
