package typegen

import (
	"fmt"
	"strings"
)

// PHP is the first multi-file emitter: one class per collection, named after
// it. Three behaviours here look like bugs and are reproduced anyway, because
// `types` output is checked into users' repositories and changing it would show
// up as an unexplained diff the first time they run the Go build:
//
//   - enum cases use toUpperSnakeCase, not sanitizeEnumKey, so an element
//     starting with a digit emits `case 9LIVES` and two elements that
//     normalise alike emit the same case twice -- neither is valid PHP
//   - the constructor lists attributes in declaration order, so an optional
//     parameter can precede a required one
//   - `array` short-circuits before the nullable suffix, so an optional array
//     attribute is typed `array`, never `array|null`
type PHP struct{}

// Type implements Language.
func (p PHP) Type(attribute Attribute, collections []Collection, collectionName string) (string, error) {
	// Returns before the nullable suffix is considered.
	if attribute.Array {
		return "array", nil
	}

	var literal string

	switch attribute.Type {
	case AttributeTypeString, AttributeTypeText, AttributeTypeVarchar,
		AttributeTypeMediumText, AttributeTypeLongText, AttributeTypeDateTime:
		literal = "string"
		if attribute.Format == AttributeTypeEnum {
			literal = ToPascalCase(collectionName) + ToPascalCase(attribute.Key)
		}
	case AttributeTypeInteger:
		literal = "int"
	case AttributeTypeFloat:
		literal = "float"
	case AttributeTypeBoolean:
		literal = "bool"
	case AttributeTypeRelationship:
		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		literal = ToPascalCase(related.Name)
		if IsRelationshipList(attribute) {
			literal = "array"
		}
	case AttributeTypePoint, AttributeTypeLineString, AttributeTypePolygon:
		literal = "array"
	default:
		return "", &UnknownAttributeTypeError{Type: attribute.Type}
	}

	if attribute.Nullable() {
		literal += "|null"
	}

	return literal, nil
}

// SingleFile implements Language.
func (p PHP) SingleFile() bool { return false }

// FileName implements Language.
func (p PHP) FileName(collection *Collection) string {
	return ToPascalCase(collection.Name) + ".php"
}

// Render implements Language.
func (p PHP) Render(collections []Collection, current *Collection, strict bool, invocation string) (string, error) {
	var out strings.Builder

	out.WriteString("<?php\nnamespace Appwrite\\Models;\n\n")
	// The trailing space after "CLI." is deliberate: the generated file is
	// pinned byte-for-byte by the baselines.
	out.WriteString("// This file is auto-generated by the Appwrite CLI. \n")
	fmt.Fprintf(&out, "// You can regenerate it by running `appwrite %s`.\n\n", invocation)

	// The import filter is NOT "everything not typed as array". It skips
	// manyToMany and oneToMany/parent only, so a manyToOne/child relationship
	// -- which IsRelationshipList also calls a list, and which PHP.Type
	// therefore types `array` -- still emits an unused import. Reproduced,
	// because it is in the shipping output.
	for _, attribute := range current.Attributes {
		if attribute.Type != AttributeTypeRelationship {
			continue
		}
		if attribute.RelationType == "manyToMany" ||
			(attribute.RelationType == "oneToMany" && attribute.Side == "parent") {
			continue
		}

		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		fmt.Fprintf(&out, "use Appwrite\\Models\\%s;\n\n", ToPascalCase(related.Name))
	}

	for _, attribute := range current.Attributes {
		if attribute.Format != AttributeTypeEnum {
			continue
		}

		fmt.Fprintf(&out, "enum %s%s: string {\n",
			ToPascalCase(current.Name), ToPascalCase(attribute.Key))
		for _, element := range attribute.Elements {
			fmt.Fprintf(&out, "    case %s = '%s';\n", ToUpperSnakeCase(element), element)
		}
		out.WriteString("}\n\n")
	}

	className := ToPascalCase(current.Name)
	fmt.Fprintf(&out, "class %s {\n", className)

	types := make([]string, len(current.Attributes))
	names := make([]string, len(current.Attributes))
	for index, attribute := range current.Attributes {
		literal, err := p.Type(attribute, collections, current.Name)
		if err != nil {
			return "", err
		}
		types[index] = literal
		names[index] = PropertyName(attribute, strict)

		fmt.Fprintf(&out, "    private %s $%s;\n", literal, names[index])
	}

	out.WriteString("\n    public function __construct(\n")
	for index, attribute := range current.Attributes {
		separator := ""
		if index < len(current.Attributes)-1 {
			separator = ","
		}

		// The declared type minus its null branch: the parameter carries
		// nullability through PHP's `?` prefix instead.
		bare := strings.ReplaceAll(types[index], "|null", "")
		if attribute.Required {
			fmt.Fprintf(&out, "        %s $%s%s\n", bare, names[index], separator)
		} else {
			fmt.Fprintf(&out, "        ?%s $%s = null%s\n", bare, names[index], separator)
		}
	}
	out.WriteString("    ) {\n")

	for _, name := range names {
		fmt.Fprintf(&out, "        $this->%s = $%s;\n", name, name)
	}
	out.WriteString("    }\n\n")

	for index, attribute := range current.Attributes {
		accessor := ToPascalCase(attribute.Key)
		fmt.Fprintf(&out, "    public function get%s(): %s {\n", accessor, types[index])
		fmt.Fprintf(&out, "        return $this->%s;\n    }\n\n", names[index])
		fmt.Fprintf(&out, "    public function set%s(%s $%s): void {\n",
			accessor, types[index], names[index])
		fmt.Fprintf(&out, "        $this->%s = $%s;\n    }\n", names[index], names[index])

		if index < len(current.Attributes)-1 {
			out.WriteString("\n")
		}
	}

	out.WriteString("}\n")

	return out.String(), nil
}
