package typegen

import (
	"fmt"
	"slices"
	"strings"
)

// The largest emitter: each collection becomes a Codable class with an
// initialiser, CodingKeys, hand-written encode/decode, toMap() and from(map:).
//
// from(map:) branches on attribute.type against literal strings, and one of
// those strings is "float" -- which no attribute ever has, because the API
// reports a float as "double". Every double therefore falls through to the
// final else and is decoded as `Double.from(map:)`, a method that does not
// exist. The same dead comparison appears in the toMap() exclusion list.
// Reproduced: it is what the TypeScript emits today, and `types` output lands
// in users' repositories where a change would read as an unexplained diff.
type Swift struct{}

// swiftStringTypes are the types from(map:) decodes straight to String.
var swiftStringTypes = []string{"string", "text", "varchar", "mediumtext", "longtext"}

// Type implements Language.
func (s Swift) Type(attribute Attribute, collections []Collection, collectionName string) (string, error) {
	var literal string

	switch attribute.Type {
	case AttributeTypeString, AttributeTypeText, AttributeTypeVarchar,
		AttributeTypeMediumText, AttributeTypeLongText, AttributeTypeDateTime:
		literal = "String"
		if attribute.Format == AttributeTypeEnum {
			literal = ToPascalCase(collectionName) + ToPascalCase(attribute.Key)
		}
	case AttributeTypeInteger:
		literal = "Int"
	case AttributeTypeFloat:
		literal = "Double"
	case AttributeTypeBoolean:
		literal = "Bool"
	case AttributeTypeRelationship:
		related, err := RelatedCollection(attribute, collections)
		if err != nil {
			return "", err
		}

		literal = ToPascalCase(related.Name)
		if IsRelationshipList(attribute) {
			literal = "[" + literal + "]"
		}
	case AttributeTypePoint:
		literal = "[Double]"
	case AttributeTypeLineString:
		literal = "[[Double]]"
	case AttributeTypePolygon:
		literal = "[[[Double]]]"
	default:
		return "", &UnknownAttributeTypeError{Type: attribute.Type}
	}

	if attribute.Array {
		literal = "[" + literal + "]"
	}
	if attribute.Nullable() {
		literal += "?"
	}

	return literal, nil
}

// SingleFile implements Language.
func (s Swift) SingleFile() bool { return false }

// FileName implements Language.
func (s Swift) FileName(collection *Collection) string {
	return ToPascalCase(collection.Name) + ".swift"
}

// unwrapped strips the optional marker, as the template's replace of the
// question mark with an empty string does. JavaScript's string replace takes
// the first occurrence only, and the suffix is only ever added once, so one
// replacement is the whole behaviour.
func unwrapped(literal string) string {
	return strings.Replace(literal, "?", "", 1)
}

// Render implements Language.
func (s Swift) Render(collections []Collection, current *Collection, strict bool, invocation string) (string, error) {
	var out strings.Builder

	// The trailing space after "CLI." is in the template.
	out.WriteString("import Foundation\n\n")
	out.WriteString("/// This file is auto-generated by the Appwrite CLI. \n")
	fmt.Fprintf(&out, "/// You can regenerate it by running `appwrite %s`.\n\n", invocation)

	for _, attribute := range current.Attributes {
		if attribute.Format != AttributeTypeEnum {
			continue
		}

		fmt.Fprintf(&out, "public enum %s%s: String, Codable, CaseIterable {\n",
			ToPascalCase(current.Name), ToPascalCase(attribute.Key))
		for _, element := range attribute.Elements {
			name := element
			if strict {
				name = ToCamelCase(element)
			}
			fmt.Fprintf(&out, "    case %s = \"%s\"\n", name, element)
		}
		out.WriteString("}\n\n")
	}

	className := ToPascalCase(current.Name)
	types := make([]string, len(current.Attributes))
	names := make([]string, len(current.Attributes))
	for index, attribute := range current.Attributes {
		literal, err := s.Type(attribute, collections, current.Name)
		if err != nil {
			return "", err
		}
		types[index] = literal
		names[index] = PropertyName(attribute, strict)
	}

	// A trailing comma is emitted on every member but the last, so each
	// section needs to know where it is in the list.
	comma := func(index int) string {
		if index < len(current.Attributes)-1 {
			return ","
		}

		return ""
	}

	fmt.Fprintf(&out, "public class %s: Codable {\n", className)
	for index := range current.Attributes {
		fmt.Fprintf(&out, "    public let %s: %s\n", names[index], types[index])
	}

	out.WriteString("\n    enum CodingKeys: String, CodingKey {\n")
	for index, attribute := range current.Attributes {
		fmt.Fprintf(&out, "        case %s = \"%s\"\n", names[index], attribute.Key)
	}
	out.WriteString("    }\n\n")

	out.WriteString("    public init(\n")
	for index := range current.Attributes {
		fmt.Fprintf(&out, "        %s: %s%s\n", names[index], types[index], comma(index))
	}
	out.WriteString("    ) {\n")
	for index := range current.Attributes {
		fmt.Fprintf(&out, "        self.%s = %s\n", names[index], names[index])
	}
	out.WriteString("    }\n\n")

	out.WriteString("    public required init(from decoder: Decoder) throws {\n")
	out.WriteString("        let container = try decoder.container(keyedBy: CodingKeys.self)\n\n")
	for index, attribute := range current.Attributes {
		decoder := "decode"
		if attribute.Nullable() {
			decoder = "decodeIfPresent"
		}
		fmt.Fprintf(&out, "        self.%s = try container.%s(%s.self, forKey: .%s)\n",
			names[index], decoder, unwrapped(types[index]), names[index])
	}
	out.WriteString("    }\n\n")

	out.WriteString("    public func encode(to encoder: Encoder) throws {\n")
	out.WriteString("        var container = encoder.container(keyedBy: CodingKeys.self)\n\n")
	for index, attribute := range current.Attributes {
		encoder := "encode"
		if attribute.Nullable() {
			encoder = "encodeIfPresent"
		}
		fmt.Fprintf(&out, "        try container.%s(%s, forKey: .%s)\n",
			encoder, names[index], names[index])
	}
	out.WriteString("    }\n\n")

	out.WriteString("    public func toMap() -> [String: Any] {\n        return [\n")
	for index, attribute := range current.Attributes {
		// "float" is dead here, as it is in from(map:), and "datetime" is
		// absent -- so an array of datetimes takes the .map { $0.toMap() }
		// branch that only makes sense for relationships.
		nested := attribute.Array && attribute.Type != AttributeTypeRelationship &&
			!slices.Contains(append(slices.Clone(swiftStringTypes), "integer", "float", "boolean"), attribute.Type)

		if nested {
			fmt.Fprintf(&out, "            \"%s\": %s?.map { $0.toMap() } as Any%s\n",
				attribute.Key, names[index], comma(index))
		} else {
			fmt.Fprintf(&out, "            \"%s\": %s as Any%s\n",
				attribute.Key, names[index], comma(index))
		}
	}
	out.WriteString("        ]\n    }\n\n")

	fmt.Fprintf(&out, "    public static func from(map: [String: Any]) -> %s {\n", className)
	fmt.Fprintf(&out, "        return %s(\n", className)
	for index, attribute := range current.Attributes {
		fmt.Fprintf(&out, "            %s\n", s.fromMapArgument(attribute, names[index], types[index], comma(index), className))
	}
	out.WriteString("        )\n    }\n}")

	return out.String(), nil
}

// fromMapArgument builds one argument of the from(map:) call.
func (s Swift) fromMapArgument(attribute Attribute, name, literal, comma, className string) string {
	// `as!` for a required attribute, `as?` for an optional one. Note this
	// keys off `required` alone, unlike the decoder above, which keys off the
	// nullable pair -- so an optional attribute with no explicit null default
	// is force-unwrapped from a value the type says can be absent.
	cast := "!"
	if !attribute.Required {
		cast = "?"
	}

	switch {
	case attribute.Type == AttributeTypeRelationship:
		return fmt.Sprintf("%s: map[\"%s\"] as%s %s%s",
			name, attribute.Key, cast, unwrapped(literal), comma)

	case attribute.Array:
		switch {
		case slices.Contains(swiftStringTypes, attribute.Type):
			return fmt.Sprintf("%s: map[\"%s\"] as%s [String]%s", name, attribute.Key, cast, comma)
		case attribute.Type == "integer":
			return fmt.Sprintf("%s: map[\"%s\"] as%s [Int]%s", name, attribute.Key, cast, comma)
		case attribute.Type == "float":
			return fmt.Sprintf("%s: map[\"%s\"] as%s [Double]%s", name, attribute.Key, cast, comma)
		case attribute.Type == "boolean":
			return fmt.Sprintf("%s: map[\"%s\"] as%s [Bool]%s", name, attribute.Key, cast, comma)
		}

		optional := ""
		if !attribute.Required {
			optional = "?"
		}

		return fmt.Sprintf("%s: (map[\"%s\"] as%s [[String: Any]])%s.map { %s.from(map: $0) }%s",
			name, attribute.Key, cast, optional, ToPascalCase(attribute.Type), comma)

	case slices.Contains(append(slices.Clone(swiftStringTypes), "email", "datetime"), attribute.Type) &&
		attribute.Format != AttributeTypeEnum:
		return fmt.Sprintf("%s: map[\"%s\"] as%s String%s", name, attribute.Key, cast, comma)

	case slices.Contains(swiftStringTypes, attribute.Type) && attribute.Format == AttributeTypeEnum:
		return fmt.Sprintf("%s: %s%s(rawValue: map[\"%s\"] as! String)!%s",
			name, className, ToPascalCase(attribute.Key), attribute.Key, comma)

	case attribute.Type == "integer":
		return fmt.Sprintf("%s: map[\"%s\"] as%s Int%s", name, attribute.Key, cast, comma)

	case attribute.Type == "float":
		return fmt.Sprintf("%s: map[\"%s\"] as%s Double%s", name, attribute.Key, cast, comma)

	case attribute.Type == "boolean":
		return fmt.Sprintf("%s: map[\"%s\"] as%s Bool%s", name, attribute.Key, cast, comma)
	}

	return fmt.Sprintf("%s: %s.from(map: map[\"%s\"] as! [String: Any])%s",
		name, ToPascalCase(attribute.Type), attribute.Key, comma)
}
