import { LanguageMeta, Attribute, Collection } from "./language.js";
import {
  getTypeScriptType,
  getAppwriteDependency,
  TypeAttribute,
  TypeEntity,
} from "../../shared/typescript-type-utils.js";

export class TypeScript extends LanguageMeta {
  getType(
    attribute: Attribute,
    collections?: Collection[],
    collectionName?: string,
  ): string {
    const typeAttribute: TypeAttribute = {
      key: attribute.key,
      type: attribute.type,
      required: attribute.required,
      array: attribute.array,
      default: attribute.default,
      format: attribute.format,
      elements: attribute.elements,
      relatedCollection: attribute.relatedCollection,
      relationType: attribute.relationType,
      side: attribute.side,
    };

    const entities: TypeEntity[] = (collections ?? []).map((c) => ({
      $id: c.$id,
      name: c.name,
    }));

    return getTypeScriptType(typeAttribute, entities, collectionName ?? "");
  }

  isSingleFile(): boolean {
    return true;
  }

  getTemplate(): string {
    const appwriteDep = getAppwriteDependency();

    return `import type { Models } from '${appwriteDep}';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running \`appwrite ${process.argv.slice(2).join(" ")}\`.

<% for (const collection of collections) { -%>
<% for (const attribute of collection.attributes) { -%>
<% if (attribute.format === 'enum') { -%>
export enum <%- toPascalCase(collection.name) %><%- toPascalCase(attribute.key) %> {
<% const entries = Object.entries(attribute.elements); -%>
<% for (let i = 0; i < entries.length; i++) { -%>
    <%- toUpperSnakeCase(entries[i][1]) %> = "<%- entries[i][1] %>"<% if (i !== entries.length - 1) { %>,<% } %>
<% } -%>
}

<% } -%>
<% } -%>
<% } -%>
<% for (const [index, collection] of Object.entries(collections)) { -%>
export type <%- toPascalCase(collection.name) %> = Models.Row & {
<% for (const attribute of collection.attributes) { -%>
<% const propertyName = strict ? toCamelCase(attribute.key) : attribute.key; -%>
<% const isValidIdentifier = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(propertyName); -%>
    <% if (isValidIdentifier) { %><%- propertyName %><% } else { %>"<%- propertyName %>"<% } %>: <%- getType(attribute, collections, collection.name) %>;
<% } -%>
}<% if (index < collections.length - 1) { %>
<% } %>
<% } -%>`;
  }

  getFileName(_: Collection | undefined): string {
    return "appwrite.d.ts";
  }
}
