name: Publish to Maven Central

on:
  release:
    types: [released]

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Prepare environment
        env:
          GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        run: |
          git fetch --unshallow
          sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
          chmod +x ./gradlew

      - name: Build Release Artifacts
        run: ./gradlew assemble

      - name: Generate Documentation
        run: ./gradlew dokkaHtml

      - name: Publish to Maven Central
        run: |
          if ${{ contains(github.event.release.tag_name, '-rc') }}; then
            echo "Publishing Snapshot Version ${{ github.event.release.tag_name}}"
            ./gradlew publishAllPublicationsToSonatypeRepository
          else
            echo "Publishing Release Version ${{ github.event.release.tag_name}}"
            ./gradlew publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository
          fi
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SDK_VERSION: ${{ github.event.release.tag_name }}
