/**
 * Auto-generated type definitions for type-safe SDK usage.
 * This file is generated by scripts/build-manifest.ts
 *
 * Run `npm run build:manifest` to regenerate this file.
 */

/** No languages available - manifest is empty */
export type Language = never;

/** Method paths mapped by language */
export type MethodPaths = Record<string, never>;

/** Service names mapped by language */
export type ServiceNames = Record<string, never>;
